services:
  - type: web
    name: ultravox-web-quickstart
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT main:application
    envVars:
      - key: ULTRAVOX_API_KEY
        scope: build
